export enum Permissions {
  // Plans
  CAN_CREATE_PLAN = 'CAN_CREATE_PLAN',
  CAN_UPDATE_PLAN = 'CAN_UPDATE_PLAN',
  CAN_DELETE_PLAN = 'CAN_DELETE_PLAN',

  //   Subscriptions
  CAN_CHANGE_SUBSCRIPTION_PLAN = 'CAN_CHANGE_SUBSCRIPTION_PLAN',
  CAN_LOCK_SUBSCRIPTION = 'CAN_LOCK_SUBSCRIPTION',
  CAN_RESUME_SUBSCRIPTION = 'CAN_RESUME_SUBSCRIPTION',
  CAN_CANCEL_SUBSCRIPTION = 'CAN_CANCEL_SUBSCRIPTION',
  CAN_UPDATE_SUBSCRIPTION = 'CAN_UPDATE_SUBSCRIPTION',
  CAN_DELETE_SUBSCRIPTION = 'CAN_DELETE_SUBSCRIPTION',

  //   Users
  CAN_CREATE_USER = 'CAN_CREATE_USER',
  CAN_UPDATE_USER = 'CAN_UPDATE_USER',
  CAN_DELETE_USER = 'CAN_DELETE_USER',
  CAN_VIEW_USERS = 'CAN_VIEW_USERS',
  CAN_CHANGE_USER_PASSWORD = 'CAN_CHANGE_USER_PASSWORD',
  CAN_CHANGE_USER_PERMISSIONS = 'CAN_CHANGE_USER_PERMISSIONS',
}
